name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Checkout vcpkg
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - name: Bootstrap vcpkg
        run: .\vcpkg\bootstrap-vcpkg.bat

      - name: Install dependencies
        run: |
          .\vcpkg\vcpkg install freetype:x64-windows-static
          .\vcpkg\vcpkg install cpr:x64-windows-static
          .\vcpkg\vcpkg install jsoncpp:x64-windows-static

      - name: Integrate vcpkg
        run: .\vcpkg\vcpkg integrate install

      - name: Build Release x64
        run: msbuild MBot.sln /m /p:Configuration=Release /p:Platform=x64
